### PR TITLE
Run proxy server always

### PR DESCRIPTION
**Pull request by jeesmon**
Run proxy server in onprem and cloud modes so that bi-directional communication can happen

Signed-off-by: Jeesmon Jacob <jjacob@us.ibm.com>

### CODE REVIEW

**Review by rduggan-ibm — COMMENTED** [review]
Let's collapse the two subjects down to one and use a naming convention to differentiate the role of each actor in the association

**Comment by jeesmon** [comment]
@rduggan-ibm Updated PR with single subject root. Please review when you get a chance.

**Review by rduggan-ibm — COMMENTED** [review]
A quick suggestion, maybe instead of PROXY/CLOUD as the actors we consider PROXY/SERVER.  There is nothing that precludes us from proxying to other types of locations.

**Comment by jeesmon** [comment]
Makes sense. Will update.

**Pull request merged**
